# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vue3shopbuild

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: set Node version
      uses: actions/setup-node@v3
      with:
        node-version: "14"
    - name: Install 
      run: npm install
    - name: link 
      run: npm run lint
    - name: runbuild  
      run: npm run build 
    - name: test
      run: npm run test:unit
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        host: 110.40.173.123
        port: 22
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: 'dist'
        target: ${{ secrets.TARGET }}
